controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    cartesian_impedance_controller:
      type: cartesian_impedance_controller/CartesianImpedanceController

    motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle

cartesian_impedance_controller:
  ros__parameters:

    # This is the tip of the robot tool that you usually use for your task.
    # For instance, it could be the drilling bit of a screwdriver or a grinding
    # tool.  When you specify a target_wrench, i.e. some additional forces that
    # your robot should apply to its environment, that target_wrench gets
    # applied in this frame.
    end_effector_link: "joint6"

    # This is usually the link directly before the first actuated joint.  All
    # controllers will build a kinematic chain from this link up to
    # end_effector_link.  It's also the reference frame for the superposition
    # of error components in all controllers.
    robot_base_link: "joint1"

    # This is the URDF link of your sensor. Sensor signals are assumed to be
    # given in this frame.  It's important that this link is located somewhere
    # between end_effector_link and robot_base_link.  If that's not the case,
    # the controllers won't initialize and will emit an error message.
    ft_sensor_ref_link: "joint6"

    # This is the link that the robot feels compliant about. It does not need
    # to coincide with the end_effector_link, but for many use cases, this
    # configuration is handy. When working with a screwdriver, for instance, 
    # setting compliance_ref_link == end_effector_link makes it easy to specify
    # downward pushing forces without generating unwanted offset moments.
    # On the other hand, an application could benefit from yielding a little in
    # the robot's wrist while drawing a line on a surface with a pen.
    compliance_ref_link: "joint6"

    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    delta_tau_max: 1.0 # Nm
    stiffness:  # w.r.t. compliance_ref_link coordinates
        trans_x: 200.0
        trans_y: 200.0
        trans_z: 200.0
        rot_x: 20.0
        rot_y: 20.0
        rot_z: 20.0
motion_control_handle:
  ros__parameters:
    end_effector_link: "joint6"
    robot_base_link: "joint1"
    ft_sensor_ref_link: "joint6"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

